#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'voice-recognition','console_scripts','stt_tts_sub'
__requires__ = 'voice-recognition'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('voice-recognition', 'console_scripts', 'stt_tts_sub')()
    )
