#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'time-alarm-handle','console_scripts','time_alarm_handle'
__requires__ = 'time-alarm-handle'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('time-alarm-handle', 'console_scripts', 'time_alarm_handle')()
    )
